sudo: enabled

dist: xenial

language: generic

branches:
  only:
    - master

git:
  submodules: false

env:
  global:
    - E3_PATH=${TRAVIS_BUILD_DIR}/epics
    - E3_SRC_PATH=${TRAVIS_BUILD_DIR}/e3
    - BASE=7.0.3
    - TAG=7.0.3
    - REQUIRE=3.1.1

    
    
    
before_install:
  - bash ${TRAVIS_BUILD_DIR}/.ci/prepare_e3.bash

install:
  - pushd e3TemplateGenerator
  - echo "EPICS_BASE:=${E3_PATH}/base-${BASE}" > RELEASE.local
  - echo "E3_REQUIRE_VERSION:=${REQUIRE}"     >> RELEASE.local
  - answer=N | bash e3TemplateGenerator.bash -m modules_conf/siteApps-template-genesysGEN5kWPS.conf -y
  - pushd e3-genesysGEN5kWPS
  - cat configure/RELEASE
  - scp ${TRAVIS_BUILD_DIR}/.ci/genesysGEN5kWPS.Makefile .
  - make vars
  - make init
  - make build
  - make install
  - make existent LEVEL=4
  - popd
  - answer=N | bash e3TemplateGenerator.bash -m modules_conf/siteMods-template-localexample.conf
  - pushd e3-example
  - cat configure/RELEASE
  - make vars
  - make build
  - make install
  - make existent LEVEL=4
  - popd
  - answer=N | bash e3TemplateGenerator.bash -m modules_conf/siteMods-template-devlib2.conf
  - pushd  e3-devlib2
  - cat configure/RELEASE
  - scp ${TRAVIS_BUILD_DIR}/.ci/devlib2.Makefile .
  - scp ${TRAVIS_BUILD_DIR}/.ci/CONFIG_MODULE configure/
  - make vars
  - make init
  - make build
  - make install
  - make existent LEVEL=4
  - popd
  - sudo rm -rf *.local
  - sudo rm -rf e3-*
  - source ${E3_PATH}/base-${BASE}/require/${REQUIRE}/bin/setE3Env.bash
  - answer=N | bash e3TemplateGenerator.bash -m modules_conf/siteApps-template-genesysGEN5kWPS.conf -y -r 
  - pushd e3-genesysGEN5kWPS
  - cat configure/RELEASE
  - scp ${TRAVIS_BUILD_DIR}/.ci/genesysGEN5kWPS.Makefile .
  - make vars
  - make init
  - make build
  - make install
  - make existent LEVEL=4
  - popd
  - answer=N | bash e3TemplateGenerator.bash -m modules_conf/siteMods-template-localexample.conf -r
  - pushd e3-example
  - cat configure/RELEASE
  - make vars
  - make build
  - make install
  - make existent LEVEL=4
  - popd
  - answer=N | bash e3TemplateGenerator.bash -m modules_conf/siteMods-template-devlib2.conf -r
  - pushd  e3-devlib2
  - cat configure/RELEASE
  - scp ${TRAVIS_BUILD_DIR}/.ci/devlib2.Makefile .
  - scp ${TRAVIS_BUILD_DIR}/.ci/CONFIG_MODULE configure/
  - make vars
  - make init
  - make build
  - make install
  - make existent LEVEL=4
  - popd
  - popd

